name: typed_data
version: 1.2.0

description: >-
  Utility functions and classes related to the dart:typed_data library.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/typed_data

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  collection: ^1.1.0

dev_dependencies:
  pedantic: '>=1.7.0 <1.8.0'
  test: ^1.0.0
