name: typed_data
version: 2.0.0-dev

description: >-
  Utility functions and classes related to the dart:typed_data library.
homepage: https://github.com/dart-lang/typed_data

environment:
  sdk: '>=2.8.0-dev.0 <3.0.0'

dependencies:
  collection: ^1.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.0.0

#dependency_overrides:
#  collection:
#    git:
#      url: git://github.com/dart-lang/collection.git
#      ref: null_safety
